# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(db_index=True, max_length=200, verbose_name='内容')),
                ('num_in', models.IntegerField(default=0, verbose_name='收入')),
                ('num_out', models.IntegerField(default=0, verbose_name='支出')),
                ('person_in', models.CharField(max_length=200, verbose_name='记账用户')),
                ('person_out', models.CharField(max_length=200, verbose_name='清账用户')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='日期')),
            ],
            options={
                'verbose_name_plural': '账单',
                'verbose_name': '账单',
            },
        ),
    ]
